### ISSUE TITLE
Fuji Testnet Address

### ISSUE THREAD

**Issue by jhb10c** [pangolindex/exchange-contracts#7]
What are the addresses for router and factory on the Fuji testnet? Im unsure where to find the addresses.

**Comment by prodesert22** [comment]
Currenty only in interface repository: [router](https://github.com/pangolindex/interface/blob/d9a4c313f8baf08f9152c863cf896d8a9e29951c/src/constants/index.ts#L9), [factory](https://github.com/pangolindex/sdk/blob/39a054548fa2a049372943170585634e666f821b/src/constants.ts#L23)  or snowtrace: [router](https://testnet.snowtrace.io/address/0x2D99ABD9008Dc933ff5c0CD271B88309593aB921), [factory](https://testnet.snowtrace.io/address/0xe4a575550c2b460d2307b82dcd7afe84ad1484dd)

- Router address: 0x2D99ABD9008Dc933ff5c0CD271B88309593aB921
- Factory address: 0xe4a575550c2b460d2307b82dcd7afe84ad1484dd
